
services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    container_name: fcxc_webapp
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:////data/fcxc_stats.db
      - VIRTUAL_HOST=xc.fchsrunning.org
    networks:
      - proxy-network
    expose:
      - "5000"

networks:
  proxy-network:
    external: true
