# Example race configuration
#
# Field descriptions:
# - meet_name: Display name for the meet/event
# - race_name: Display name for the specific race (e.g., "Varsity Boys", "JV Girls")
# - url: MileSplit formatted results URL (for online scraping)
# - file: Local HTML file path (for offline parsing)
# - distance: Race distance (e.g., "5K", "3K", "1600m")
# - race_class: Race category (e.g., "varsity", "jv", "freshman")
# - gender: "boys", "girls", or "mixed"
# - date: Race date in YYYY-MM-DD format
# - season: Year of the season
# 
# Use either 'url' for online scraping or 'file' for local HTML files

races:
  # Liberty Bell Cross Country Invitational 2025 - September 13, 2025
  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Mens 5,000 Meters Saucony Sweepstakes Varsity Results"

  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Womens 5,000 Meters Runners Roost Sweepstakes Varsity Results"

  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Mens 5,000 Meters Sweepstakes JV Results"

  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Womens 5,000 Meters Sweepstakes JV Results"

  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "Open Boys"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Mens 5,000 Meters Sweepstakes Open Results"

  - meet_name: "Liberty Bell Cross Country Invitational 2025"
    race_name: "Open Girls"
    file: "pages/Liberty Bell Cross Country Invitational 2025 - Complete (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Heritage High School XC Course"
    date: "2025-09-13"
    season: "2025"
    algorithm: raw_combined
    results_title: "Womens 5,000 Meters Sweepstakes Open Results"

  # Windsor Wizards Invitational 2025 - September 21, 2025
  - meet_name: "Windsor Wizards Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Windsor Wizards Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Windsor High School"
    date: "2025-09-21"
    season: "2025"
    algorithm: raw_windsor_combined
    results_title: "Windsor HS Varsity Boys"

  - meet_name: "Windsor Wizards Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Windsor Wizards Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Windsor High School"
    date: "2025-09-21"
    season: "2025"
    algorithm: raw_windsor_combined
    results_title: "Windsor HS Varsity Girls"

  - meet_name: "Windsor Wizards Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Windsor Wizards Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Windsor High School"
    date: "2025-09-21"
    season: "2025"
    algorithm: raw_windsor_combined
    results_title: "Windsor HS JV Boys"

  - meet_name: "Windsor Wizards Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Windsor Wizards Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Windsor High School"
    date: "2025-09-21"
    season: "2025"
    algorithm: raw_windsor_combined
    results_title: "Windsor HS JV Girls"

  # Thornton Cross Country Invitational 2025 - September 5, 2025
  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  # John Martin XC Invitational 2025 - August 30, 2025
  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Boys JV"
    file: "pages/John Martin XC Invitational 2025 - High School Boys JV 5000 Meter (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Boys Varsity"
    file: "pages/John Martin XC Invitational 2025 - High School Boys Varsity 5000 Me (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Girls JV"
    file: "pages/John Martin XC Invitational 2025 - High School Girls JV 5000 Meter (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Girls Varsity"
    file: "pages/John Martin XC Invitational 2025 - High School Girls Varsity 5000 M (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  # Rocky Mountain Lobo Invitational 2025 - August 23, 2025
  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - Varsity Boys (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - Varsity Girls (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - JV Boys (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - JV Girls (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  # Vista Nation XC 2-Mile Invitational 2025 - August 23, 2025
  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Boys Varsity"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Boys Varsity (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "boys"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Girls Varsity"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Girls Varsity (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "girls"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Boys Freshman/Sophomore"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Boys Freshman_Sophomore (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "boys"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Girls Freshman/Sophomore"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Girls Freshman_Sophomore (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "girls"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default
    

# Example of raw_combined algorithm configuration
# This algorithm parses results from a combined HTML file using a results_title to find specific sections
# Uncomment and modify these entries to use the raw_combined algorithm:
#
#  - meet_name: "Example Combined Meet 2025"
#    race_name: "JV Boys"
#    file: "pages/Example Combined Meet 2025 - Results.html"
#    distance: "5K"
#    race_class: "jv"
#    gender: "boys"
#    venue: "Example Venue"
#    date: "2025-09-15"
#    season: "2025"
#    algorithm: raw_combined
#    results_title: "JV Boys 5000 Meter Run"
#
#  - meet_name: "Example Combined Meet 2025"
#    race_name: "JV Girls"
#    file: "pages/Example Combined Meet 2025 - Results.html"
#    distance: "5K"
#    race_class: "jv"
#    gender: "girls"
#    venue: "Example Venue"
#    date: "2025-09-15"
#    season: "2025"
#    algorithm: raw_combined
#    results_title: "JV Girls 5000 Meter Run"
#
#  - meet_name: "Example Combined Meet 2025"
#    race_name: "Varsity Boys"
#    file: "pages/Example Combined Meet 2025 - Results.html"
#    distance: "5K"
#    race_class: "varsity"
#    gender: "boys"
#    venue: "Example Venue"
#    date: "2025-09-15"
#    season: "2025"
#    algorithm: raw_combined
#    results_title: "Varsity Boys 5000 Meter Run"
#
#  - meet_name: "Example Combined Meet 2025"
#    race_name: "Varsity Girls"
#    file: "pages/Example Combined Meet 2025 - Results.html"
#    distance: "5K"
#    race_class: "varsity"
#    gender: "girls"
#    venue: "Example Venue"
#    date: "2025-09-15"
#    season: "2025"
#    algorithm: raw_combined
#    results_title: "Varsity Girls 5000 Meter Run"

  # Desert Twilight XC Invite 2025 - September 26, 2025
  - meet_name: "Desert Twilight XC Invite 2025"
    race_name: "Boys Sweepstakes"
    file: "pages/Desert Twilight Boys.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Toka Sticks Golf Course, AZ"
    date: "2025-09-26"
    season: "2025"
    algorithm: desert_twilight
    results_title: "Mens 5,000 Meters Sweepstakes"

  - meet_name: "Desert Twilight XC Invite 2025"
    race_name: "Girls Sweepstakes"
    file: "pages/Desert Twilight Girls.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Toka Sticks Golf Course, AZ"
    date: "2025-09-26"
    season: "2025"
    algorithm: desert_twilight
    results_title: "Womens 5,000 Meters Sweepstakes"

  # Loveland Sweetheart 2025 - September 27, 2025
  - meet_name: "Loveland Sweetheart 2025"
    race_name: "Varsity Boys"
    file: "pages/Loveland Sweetheart 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Loveland High School"
    date: "2025-09-27"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "HS Varsity Boys 5K"

  - meet_name: "Loveland Sweetheart 2025"
    race_name: "Varsity Girls"
    file: "pages/Loveland Sweetheart 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Loveland High School"
    date: "2025-09-27"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "HS Varsity Girls 5K"

  # Hawk JV Championships 2025 - October 17, 2025
  - meet_name: "Hawk JV Championships 2025"
    race_name: "JV Boys"
    file: "pages/Hawk JV Champs 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Adams County Regional Park XC Course"
    date: "2025-10-17"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "Boys 5000 Meters"

  - meet_name: "Hawk JV Championships 2025"
    race_name: "JV Girls"
    file: "pages/Hawk JV Champs 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Adams County Regional Park XC Course"
    date: "2025-10-17"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "Girls 5000 Meters"

  - meet_name: "Loveland Sweetheart 2025"
    race_name: "JV Boys"
    file: "pages/Loveland Sweetheart 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Loveland High School"
    date: "2025-09-27"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "Boys HS Open 5K"

  - meet_name: "Loveland Sweetheart 2025"
    race_name: "JV Girls"
    file: "pages/Loveland Sweetheart 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Loveland High School"
    date: "2025-09-27"
    season: "2025"
    algorithm: loveland_sweetheart
    results_title: "Girls HS Open 5K"

  # Longs Peak Invitational 2025 - October 3, 2025
  - meet_name: "Longs Peak Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Longs Peak Invite Boys 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Estes Park HS XC Course"
    date: "2025-10-03"
    season: "2025"
    algorithm: longs_peak

  - meet_name: "Longs Peak Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Longs Peak Invite Girls 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Estes Park HS XC Course"
    date: "2025-10-03"
    season: "2025"
    algorithm: longs_peak

  # Northern Conference Championships 2025 - October 10, 2025
  - meet_name: "Northern Conference Championships 2025"
    race_name: "Varsity Boys"
    file: "pages/Northern Conference Champs 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Spring Canyon Park"
    date: "2025-10-10"
    season: "2025"
    algorithm: northern_conference
    race_number: 3

  - meet_name: "Northern Conference Championships 2025"
    race_name: "Varsity Girls"
    file: "pages/Northern Conference Champs 2025.txt"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Spring Canyon Park"
    date: "2025-10-10"
    season: "2025"
    algorithm: northern_conference
    race_number: 4

  - meet_name: "Northern Conference Championships 2025"
    race_name: "JV Boys"
    file: "pages/Northern Conference Champs 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Spring Canyon Park"
    date: "2025-10-10"
    season: "2025"
    algorithm: northern_conference
    race_number: 5

  - meet_name: "Northern Conference Championships 2025"
    race_name: "JV Girls"
    file: "pages/Northern Conference Champs 2025.txt"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Spring Canyon Park"
    date: "2025-10-10"
    season: "2025"
    algorithm: northern_conference
    race_number: 6

# Team information
team:
  name: "Fort Collins High School"
  abbreviation: "FCHS"
  colors:
    primary: "#FF0000"
    secondary: "#FFFFFF"

