# Example race configuration
#
# Field descriptions:
# - meet_name: Display name for the meet/event
# - race_name: Display name for the specific race (e.g., "Varsity Boys", "JV Girls")
# - url: MileSplit formatted results URL (for online scraping)
# - file: Local HTML file path (for offline parsing)
# - distance: Race distance (e.g., "5K", "3K", "1600m")
# - race_class: Race category (e.g., "varsity", "jv", "freshman")
# - gender: "boys", "girls", or "mixed"
# - date: Race date in YYYY-MM-DD format
# - season: Year of the season
# 
# Use either 'url' for online scraping or 'file' for local HTML files

races:
  # Thornton Cross Country Invitational 2025 - September 5, 2025
  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  - meet_name: "Thornton Cross Country Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Thornton Cross Country Invitational 2025 - Complete Results (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Thornton High School"
    date: "2025-09-05"
    season: "2025"
    algorithm: thornton_combined

  # John Martin XC Invitational 2025 - August 30, 2025
  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Boys JV"
    file: "pages/John Martin XC Invitational 2025 - High School Boys JV 5000 Meter (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Boys Varsity"
    file: "pages/John Martin XC Invitational 2025 - High School Boys Varsity 5000 Me (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Girls JV"
    file: "pages/John Martin XC Invitational 2025 - High School Girls JV 5000 Meter (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  - meet_name: "John Martin XC Invitational 2025"
    race_name: "High School Girls Varsity"
    file: "pages/John Martin XC Invitational 2025 - High School Girls Varsity 5000 M (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Fort Collins High School"
    date: "2025-08-30"
    season: "2025"
    algorithm: john_martin

  # Rocky Mountain Lobo Invitational 2025 - August 23, 2025
  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "Varsity Boys"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - Varsity Boys (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "boys"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "Varsity Girls"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - Varsity Girls (Raw).html"
    distance: "5K"
    race_class: "varsity"
    gender: "girls"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "JV Boys"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - JV Boys (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "boys"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Rocky Mountain Lobo Invitational 2025"
    race_name: "JV Girls"
    file: "pages/Rocky Mountain Lobo Invitational 2025 - JV Girls (Raw).html"
    distance: "5K"
    race_class: "jv"
    gender: "girls"
    venue: "Rocky Mountain High School, Fort Collins CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  # Vista Nation XC 2-Mile Invitational 2025 - August 23, 2025
  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Boys Varsity"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Boys Varsity (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "boys"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Girls Varsity"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Girls Varsity (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "girls"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Boys Freshman/Sophomore"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Boys Freshman_Sophomore (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "boys"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default

  - meet_name: "Vista Nation XC 2-Mile Invitational 2025"
    race_name: "Girls Freshman/Sophomore"
    file: "pages/Vista Nation XC 2-Mile Invitational 2025 - Girls Freshman_Sophomore (Raw).html"
    distance: "2M"
    race_class: "varsity"
    gender: "girls"
    venue: "Mountain Vista High School, Highlands Ranch CO"
    date: "2025-08-23"
    season: "2025"
    algorithm: default
    

# Team information
team:
  name: "Fort Collins High School"
  abbreviation: "FCHS"
  colors:
    primary: "#FF0000"
    secondary: "#FFFFFF"
